language:
    - cpp

install:
    - sudo apt-get install build-essential
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-4.9
    - sudo apt-get install build-essential cmake
    - cd /usr/bin
    - sudo rm g++ 
    - sudo ln -s g++-4.9 g++
    - sudo wget https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
    - sudo gunzip protobuf-2.5.0.tar.gz 
    - sudo tar -xvf protobuf-2.5.0.tar
    - cd protobuf-2.5.0
    - sudo ./configure --prefix=/usr
    - sudo make
    - sudo make install
    - cd ~
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install valgrind
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libgtest* /usr/lib/
    - cd "${TRAVIS_BUILD_DIR}"
    - cd yadb
    
script:
    - mkdir builds
    - cd builds
    - cmake -Dtest=ON ..
    - make
    - make test ARGS="-V"
